on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Rust Build Check

jobs:
  build_and_test:
    name: Rust Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
